application: weighttracking
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /
  script: main.app

- url: /opened
  script: main.app

- url: /index\.html
  script: main.app

- url: /data
  script: data.app

- url: /css
  static_dir: css

- url: /js
  static_dir: js

- url: /fonts
  static_dir: fonts

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest

builtins:
- deferred: on
